# Generated by Django 4.1.7 on 2023-12-18 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_rename_phone_profile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='antro_id',
            field=models.CharField(default='', max_length=10, unique=True),
        ),
    ]
