# Generated by Django 4.1.7 on 2023-12-18 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_profile_antro_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='antro_id',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
    ]
