# Generated by Django 4.1.7 on 2024-01-03 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_profile_active_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='verified_by_antro',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='verified_by_organisation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='verified_by_user',
            field=models.BooleanField(default=False),
        ),
    ]
