# Generated by Django 4.1.7 on 2024-01-19 11:26

import antrobackend.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0014_alter_profile_options_remove_profile_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=antrobackend.storage_backends.PublicMediaStorage(), upload_to=''),
        ),
    ]
