# Generated by Django 4.1.7 on 2023-03-06 08:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_date_of_birth'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestData',
            fields=[
                ('data', models.JSONField(default={})),
                ('request_id', models.UUIDField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userrequestdata', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
