# Generated by Django 4.1.7 on 2023-09-15 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_organisation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='social_media_links',
            field=models.JSONField(blank=True, null=True, verbose_name='Social Media Links'),
        ),
    ]
