# Generated by Django 4.1.7 on 2023-03-08 04:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_requestdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestdata',
            name='data',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='requestdata',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
