# Generated by Django 4.1.7 on 2023-09-21 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0015_remove_location_members_branch'),
        ('users', '0006_alter_organisation_social_media_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organisation.branch'),
        ),
    ]
