# Generated by Django 4.1.7 on 2023-09-21 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_userprofile_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='location',
            new_name='branch',
        ),
    ]
