# Generated by Django 4.1.7 on 2023-06-09 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_requestdata_data_alter_requestdata_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='awards_recognitions',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='conference_event',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='contact_information',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='languages',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='personal_website',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='projects',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
