# Generated by Django 4.1.7 on 2023-09-21 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_rename_location_userprofile_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='initial_members_added',
            field=models.BooleanField(default=False),
        ),
    ]
