# Generated by Django 4.1.7 on 2023-11-04 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_organisation_initial_members_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verified_by_antro',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='verified_by_organisation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='verified_by_user',
            field=models.BooleanField(default=False),
        ),
    ]
