# Generated by Django 4.1.7 on 2023-11-04 09:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_documentcategory_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentcategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 11, 4, 9, 57, 9, 828779, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
