# Generated by Django 4.1.7 on 2023-11-04 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_rename_is_active_userprofile_active_user_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='documentcategory',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
