# Generated by Django 4.1.7 on 2023-11-05 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_document_active_documentcategory_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='onboarding_complete',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='OnboardingLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret', models.UUIDField(unique=True)),
                ('link_to_email', models.EmailField(max_length=255, verbose_name='Link Email')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
