# Generated by Django 4.1.7 on 2023-11-07 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_resetpasswordverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='coporate',
            field=models.BooleanField(default=False),
        ),
    ]
