# Generated by Django 4.1.7 on 2023-11-07 14:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0021_broadcastmessage_edited_alter_group_messages'),
        ('users', '0019_userprofile_coporate'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempUserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(blank=True, default='', max_length=200)),
                ('gender', models.CharField(blank=True, default='', max_length=20)),
                ('contact_information', models.CharField(blank=True, max_length=50, null=True)),
                ('awards_recognitions', models.CharField(blank=True, max_length=1000, null=True)),
                ('personal_website', models.CharField(blank=True, max_length=1000, null=True)),
                ('conference_event', models.CharField(blank=True, max_length=1000, null=True)),
                ('languages', models.CharField(blank=True, max_length=1000, null=True)),
                ('projects', models.CharField(blank=True, max_length=1000, null=True)),
                ('active', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organisation.branch')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tempuserprofile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TempUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=254, null=True)),
                ('last_name', models.CharField(blank=True, max_length=254, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('onboarding_complete', models.BooleanField(default=True)),
                ('organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.organisation')),
            ],
        ),
        migrations.AlterField(
            model_name='onboardinglink',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.tempuser'),
        ),
    ]
