# Generated by Django 4.1.7 on 2023-11-07 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_tempuserprofile_tempuser_alter_onboardinglink_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempuserprofile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tempuserprofile', to='users.tempuser'),
        ),
    ]
