# Generated by Django 4.1.7 on 2023-11-14 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_rename_user_id_user_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='user_id',
        ),
    ]
