# Generated by Django 4.1.7 on 2023-12-07 15:35

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_profilelike_profilecomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempuser',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
