# Generated by Django 4.1.7 on 2023-12-07 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_tempuser_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onboardinglink',
            name='secret',
        ),
        migrations.AddField(
            model_name='onboardinglink',
            name='android_deeplink_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
