# Generated by Django 4.1.7 on 2023-12-18 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_tempuserstatus_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempuserstatus',
            name='otp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tempuserstatus',
            name='verification_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
