# Generated by Django 4.1.7 on 2023-12-18 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0038_tempuserstatus_otp_tempuserstatus_verification_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tempuserstatus',
            name='otp',
        ),
        migrations.RemoveField(
            model_name='tempuserstatus',
            name='verification_time',
        ),
        migrations.AddField(
            model_name='tempuser',
            name='otp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tempuser',
            name='verification_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
