# Generated by Django 4.1.7 on 2023-12-18 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_remove_tempuserstatus_otp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempuserprofile',
            name='Certifications',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='tempuserprofile',
            name='Education',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tempuserprofile',
            name='Experience',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tempuserprofile',
            name='Skills',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
