# Generated by Django 4.1.7 on 2023-12-18 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0040_tempuserprofile_certifications_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tempuserprofile',
            old_name='Certifications',
            new_name='certifications',
        ),
        migrations.RenameField(
            model_name='tempuserprofile',
            old_name='Education',
            new_name='education',
        ),
        migrations.RenameField(
            model_name='tempuserprofile',
            old_name='Experience',
            new_name='experience',
        ),
        migrations.RenameField(
            model_name='tempuserprofile',
            old_name='Skills',
            new_name='skills',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='Education',
            new_name='education',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='Experience',
            new_name='experience',
        ),
    ]
