# Generated by Django 4.1.7 on 2023-12-19 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0044_tempuserstatus_failed_reason_tempuserstatus_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempuserstatus',
            name='upload_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('failed', 'Failed'), ('completed', 'Completed')], default='Pending', max_length=10),
        ),
    ]
