# Generated by Django 4.1.7 on 2024-01-19 11:26

import antrobackend.storage_backends
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0046_userprofile_profiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(storage=antrobackend.storage_backends.PublicMediaStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='logo',
            field=models.ImageField(blank=True, null=True, storage=antrobackend.storage_backends.PublicMediaStorage(), upload_to='', verbose_name='Company Logo'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=antrobackend.storage_backends.PublicMediaStorage(), upload_to=''),
        ),
        migrations.CreateModel(
            name='AuthenticationEntity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=254, null=True)),
                ('last_name', models.CharField(blank=True, max_length=254, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('image_url', models.URLField()),
                ('otp', models.IntegerField(default=0)),
                ('gesture', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('0', 'Pending'), ('1', 'Verified'), ('2', 'Failed')], default='0', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
