# Generated by Django 4.1.7 on 2024-01-19 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0047_alter_document_file_alter_organisation_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authenticationentity',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
