# Generated by Django 4.1.7 on 2023-09-10 07:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='level',
            field=models.CharField(choices=[('0', 'Global'), ('1', 'Continent'), ('2', 'Country'), ('3', 'State'), ('4', 'City'), ('5', 'Local')], default='0', max_length=50),
        ),
        migrations.AlterField(
            model_name='group',
            name='organisation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='organisation.organisation'),
            preserve_default=False,
        ),
    ]
