# Generated by Django 4.1.7 on 2023-09-10 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0007_alter_organisation_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='parent',
        ),
    ]
