# Generated by Django 4.1.7 on 2023-09-10 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0008_remove_group_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='participants',
        ),
        migrations.AddField(
            model_name='group',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organisation.group'),
        ),
    ]
