# Generated by Django 4.1.7 on 2023-09-10 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0009_remove_group_participants_group_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='messages',
        ),
    ]
