# Generated by Django 4.1.7 on 2023-09-10 09:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organisation', '0010_remove_group_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='messages',
            field=models.ManyToManyField(blank=True, to='organisation.broadcastmessage'),
        ),
        migrations.AddField(
            model_name='group',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='broadcast_groups', to=settings.AUTH_USER_MODEL),
        ),
    ]
