# Generated by Django 4.1.7 on 2023-09-20 08:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_organisation_social_media_links'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organisation', '0012_alter_group_organisation_delete_organisation'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('level', models.CharField(choices=[('0', 'Global'), ('1', 'Continent'), ('2', 'Country'), ('3', 'State'), ('4', 'City'), ('5', 'Local')], default='0', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('members', models.ManyToManyField(blank=True, related_name='company_members', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.organisation')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organisation.companylocation')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
