# Generated by Django 4.1.7 on 2023-09-20 08:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0006_alter_organisation_social_media_links'),
        ('organisation', '0013_companylocation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CompanyLocation',
            new_name='Location',
        ),
    ]
