# Generated by Django 4.1.7 on 2023-09-21 08:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_organisation_social_media_links'),
        ('organisation', '0014_rename_companylocation_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='members',
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('branch_name', models.CharField(max_length=100)),
                ('branch_address', models.CharField(blank=True, max_length=200, null=True)),
                ('branch_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organisation.location')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.organisation')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
