# Generated by Django 4.1.7 on 2023-09-25 07:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_organisation_initial_members_added'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organisation', '0016_alter_branch_location_alter_group_parent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchBroadcastHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branches', models.ManyToManyField(blank=True, related_name='broadcast_history', to='organisation.branch')),
                ('broadcast_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('broadcast_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisation.location')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.organisation')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
