# Generated by Django 4.1.7 on 2023-10-14 12:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organisation', '0018_remove_group_participants_groupparticipants'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='broadcast_groups', through='organisation.GroupParticipants', to=settings.AUTH_USER_MODEL),
        ),
    ]
