# Generated by Django 4.1.7 on 2023-10-16 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0019_group_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcastmessage',
            name='combine_id',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
