# Generated by Django 4.1.7 on 2023-10-16 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0020_broadcastmessage_combine_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcastmessage',
            name='edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='group',
            name='messages',
            field=models.ManyToManyField(blank=True, related_name='group', to='organisation.broadcastmessage'),
        ),
    ]
