# Generated by Django 4.1.7 on 2023-11-14 07:39

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0021_broadcastmessage_edited_alter_group_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='branch_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
