# Generated by Django 4.1.7 on 2023-03-17 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_rename_shop_card'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Keywords',
            new_name='Keyword',
        ),
    ]
