# Generated by Django 4.1.7 on 2023-06-06 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_card_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='field',
            new_name='profession',
        ),
    ]
